export const CHARTS_UTILS = {
    ALMACENES_PROPIEDAD: 'ALMACENES EN PROPIEDAD',
    TOTAL_GANANCIAS: 'TOTAL DE GANANCIAS',
    MERCANCIA_ESPECIAL: 'MERCANCÍA ESPECIAL EN PROPIEDAD',
    CAPACIDAD_MAX: 'CAPACIDAD MÁXIMA',
    OCUPADO: 'OCUPADO',
    ESPACIO_LIBRE: 'ESPACIO LIBRE',
    DARK_RED: '#90221c',
    LIGHT_RED: '#c02a2b',
    GRAY_PATTERN: '#939393',
    LINES_PATTERN: '#1c1c1c',
    GRID_COLOR: '#2b2929'
};